### ISSUE TITLE
`-PnoDirtyCheck=true` no longer works

### ISSUE THREAD

**Issue by tacascer** [jmongard/Git.SemVersioning.Gradle#55] opened 2024-02-26 16:52 UTC
It seems that `-PnoDirtyCheck=true` is no longer being honored by the `releaseVersion` task. 

A short investigation shows that the task defaults the property to false [here](https://github.com/jmongard/Git.SemVersioning.Gradle/blob/master/src/main/kotlin/git/semver/plugin/gradle/ReleaseTask.kt#L16).

The only manipulation of the field I can find is [here](https://github.com/jmongard/Git.SemVersioning.Gradle/blob/master/src/main/kotlin/git/semver/plugin/gradle/ReleaseTask.kt#L53-L56).

It seems that the property is not being passed down from the `settings` object passed in.

**Comment by jmongard** [comment] 2024-02-28 09:30
Ok, I will look in to it

**Comment by jmongard** [comment] 2024-02-28 21:07
This problem is fixed in 0.12.5. It were caused by requirement to reading properties lazy to make configuration cache work. The properties were only read when using the print tasks but not when using the release task.

**Closed** 2024-02-28 21:08 UTC
