### ISSUE TITLE
Changelog for release candidate contains full commit history

### ISSUE THREAD

**Issue by mnonnenmacher** [jmongard/Git.SemVersioning.Gradle#61] opened 2024-10-16 16:22 UTC
In my repository (https://github.com/eclipse-apoapsis/ort-server) I have two tags: `0.1.0-RC1` and `0.1.0-RC2`

When I run `./gradlew printChangelog` on tag `0.1.0-RC2` I would have expected that it only contains the commits since the previous release candidate `0.1.0-RC1`, but it contains the full commit history. If I add a release tag `0.0.1` somewhere in the history, then the output contains only the commits up to this release tag. So it seems that `printChangelog` ignores release candidates. This makes it difficult to figure out what additional changes `RC2` contains compared to `RC1`, especially if there are many commits.

Would it be possible to alter the behavior so that `printChangelog` does not ignore previous release candidates if the last tag is also a release candidate?

**Comment by jmongard** [comment] 2024-10-16 22:46
Hi,
It is by design that the plugin looks for the last non pre-release tag/commit for calculating the next version. However when it comes to generating change log I don't think it is desirable.
I will look into it and se how it can be improved.

**Comment by jmongard** [comment] 2024-10-18 07:26
This issue should be fixed in version `0.12.11`

**Comment by sschuberth** [comment] 2024-10-18 08:07
Confirmed to be fixed, thanks for the fast action!

**Closed** 2024-10-18 12:26 UTC
